export const LIMITS = {
  TWEET_MAX_LENGTH: 1500,
  THREAD_MAX_LENGTH: 10,
  IMAGE_MAX_SIZE_MB: 10,
  IMAGE_MAX_WIDTH: 4096,
  IMAGE_MAX_HEIGHT: 4096,
  KOL_PROFILES_FREE: 3,
  KOL_PROFILES_PRO: 50,
  KOL_PROFILES_ENTERPRISE: 999,
  GENERATIONS_FREE_MONTHLY: 10,
  GENERATIONS_PRO_MONTHLY: 100,
  GENERATIONS_ENTERPRISE_MONTHLY: 1000,
} as const;
